# Generated by Django 2.1.7 on 2021-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_js', '0002_js_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_blogtype',
            name='type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
