# Generated by Django 3.2.4 on 2021-06-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_js', '0004_alter_js_blogtype_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_blogs',
            name='blog_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog_js.js_blogtype'),
            preserve_default=False,
        ),
    ]
