# Generated by Django 3.2.4 on 2021-06-18 15:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_js', '0005_alter_js_blogs_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='js_blogs',
            name='blog_hashtags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer', 'Computer'), ('Math', 'Math'), ('Eng', 'Eng'), ('Technology', 'Technology')], max_length=255, null=True),
        ),
    ]
