# Generated by Django 2.1.7 on 2021-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210611_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, choices=[('UpSkills', 'UpSkills'), ('Recommend', 'Recommend'), ('Genneral', 'Genneral')], max_length=120, null=True)),
            ],
        ),
    ]
