# Generated by Django 2.1.7 on 2021-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtags',
            name='tag_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
