# Generated by Django 2.1.7 on 2021-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210611_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_hashtags',
            field=models.ManyToManyField(to='blogs.BlogTags'),
        ),
    ]
