# Generated by Django 2.1.7 on 2021-06-13 07:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogs_blog_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_hashtags',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_hashtags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('UpSkills', 'UpSkills'), ('Recommend', 'Recommend'), ('Genneral', 'Genneral')], max_length=27, null=True),
        ),
    ]
