# Generated by Django 2.1.7 on 2021-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210613_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtags',
            name='key_tag_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
