# Generated by Django 2.1.7 on 2021-06-13 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210613_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_hashtags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, (('Upskills', 'upskills'),)), (2, (('Recommend', 'recommend'),)), (3, (('Genneral', 'genneral'),)), (4, (('Food', 'food'),))], max_length=255, null=True),
        ),
    ]
