# Generated by Django 2.1.7 on 2021-06-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210613_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtags',
            name='key_tag_name',
        ),
    ]
