# Generated by Django 2.1.7 on 2021-06-14 11:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_blogtags_key_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_hashtags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Upskills'), (2, 'Recommend'), (3, 'Genneral'), (4, 'Food'), (5, 'New')], max_length=255, null=True),
        ),
    ]
