# Generated by Django 2.1.7 on 2021-07-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0002_nationalitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('hn', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title_th', models.CharField(blank=True, max_length=120, unique=True)),
                ('f_name_th', models.CharField(blank=True, max_length=120, unique=True)),
                ('l_name_th', models.CharField(blank=True, max_length=120, unique=True)),
                ('m_name_th', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('home', models.CharField(blank=True, max_length=120, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=120, unique=True)),
                ('f_name_en', models.CharField(blank=True, max_length=120, unique=True)),
                ('l_name_en', models.CharField(blank=True, max_length=120, unique=True)),
                ('m_name_en', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('work', models.CharField(blank=True, max_length=120, unique=True)),
                ('work_phone_exten', models.CharField(blank=True, max_length=120, unique=True)),
                ('main_fax', models.CharField(blank=True, max_length=120, unique=True)),
                ('age', models.IntegerField(blank=True, max_length=3)),
                ('gender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact_js.GendersModel')),
                ('nationality', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact_js.NationalityModel')),
            ],
        ),
    ]
