# Generated by Django 2.1.7 on 2021-07-01 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0005_auto_20210701_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
