# Generated by Django 2.1.7 on 2021-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0009_contactmodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='title_th',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
