# Generated by Django 2.1.7 on 2021-07-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0011_emailtypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_email', models.CharField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, unique=True)),
                ('primary_status', models.BooleanField(default=False)),
                ('contact_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact_js.ContactModel')),
                ('phone_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contact_js.EmailTypeModel')),
            ],
        ),
    ]
