# Generated by Django 2.2 on 2021-07-13 08:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0016_alternatephonemodel_test_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatephonemodel',
            name='test_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=10, null=True, region=None),
        ),
    ]
