# Generated by Django 2.2 on 2021-07-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0019_auto_20210713_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternatephonemodel',
            name='test_phone',
        ),
    ]
