# Generated by Django 2.2 on 2021-07-13 16:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0020_remove_alternatephonemodel_test_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatephonemodel',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='TH'),
        ),
    ]
