# Generated by Django 2.2 on 2021-07-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0021_auto_20210713_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateemailmodel',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
