# Generated by Django 2.2 on 2021-07-22 03:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0024_testcheckboxmodel_chk_dender2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcheckboxmodel',
            name='chk_dender2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Female/ผู้หญิง'), (2, 'Male/ผู้ชาย'), (3, 'Other/อื่นๆ'), (4, 'None/ไม่ระบุเพศ')], max_length=7, null=True),
        ),
    ]
