# Generated by Django 2.2 on 2021-07-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_js', '0027_auto_20210722_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcheckboxmodel',
            name='chk_dender2',
        ),
    ]
